# Generated by Django 6.0.6 on 2026-07-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
