# Generated by Django 6.0.6 on 2026-07-06 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_alter_event_color_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Salary', 'Salary'), ('Business', 'Business'), ('Freelancing', 'Freelancing'), ('Investment', 'Investment'), ('Other Income', 'Other Income'), ('Food', 'Food'), ('Shopping', 'Shopping'), ('Bills', 'Bills'), ('Transport', 'Transport'), ('Medical', 'Medical'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Travel', 'Travel'), ('Other Expense', 'Other Expense')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
